name = "Hubert"
description = "Hubert's voice conjures images of old decrepit malevolent wizards. But his grating shrill voice will fit anywhere you want to have a frail old man that you intend for your audience to dislike."

tags = [
"creepy",
"feeble",
"high-pitched",
]
