name = "Tamlin"
description = "Somewhat inspired by the character of the same name in the show, Vox Machina, Tamlin's voice fits within the role of bard, radio host, corporate goon, and more. You don't necessarily like him, but you would probably buy whatever he is selling."

tags = [
"confident",
"insincere",
"cheesy",
]
